name: artifactdownload
on: push
env: 
    ARTIFACT_NAME: myartifact
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: Upload
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ env.ARTIFACT_NAME }}
                  path: .

              
