name: artifactdownload
on: push
env: 
    ARTIFACT_NAME: myartifact
jobs:
    main:
        runs-on: ubuntu-latest
        container:
            image: node:14.16
            volumes:
            - "${{ github.workspace }} :/code"
        steps:
            - name: checkout
              uses: actions/checkout@v2

              
